input_mode:
  actuators:             false
  control_group:         false
  attitude_rate:         false
  attitude:              false
  acceleration_hdg_rate: false
  acceleration_hdg:      false
  velocity_hdg_rate:     true
  velocity_hdg:          false
  position:              false

  feedforward: true

outputs:
  distance_sensor:      false
  gnss:                 false
  rtk:                  false
  imu:                  false
  altitude:             false
  magnetometer_heading: false
  rc_channels:          false
  battery_state:        false
  position:             false
  orientation:          false
  velocity:             false
  angular_velocity:     false
  odometry:             true
  ground_truth:         false
