main_rate: 10.0 # [Hz]
swarming_rate: 10.0 # [Hz]

swarming:
  max_velocity: 2.0 # (m/s)
  visibility_radius: 10.0 # (m)

uav_names: [
  "uav1",
  "uav2",
  "uav3",
  "uav4",
  "uav5",
  "uav6",
  "uav7",
  "uav8",
  "uav9",
  "uav10",
  "uav11",
  "uav12",
  "uav13",
  "uav14",
  "uav15",
  "uav16",
  "uav17",
  "uav18",
  "uav19",
  "uav20",
  "uav21",
  "uav22",
  "uav23",
  "uav24",
  "uav25",
  "uav26",
  "uav27",
  "uav28",
  "uav29",
  "uav30",
  "uav31",
  "uav32",
  "uav33",
  "uav34",
  "uav35",
  "uav36",
  "uav37",
  "uav38",
  "uav39",
  "uav40",
  "uav41",
  "uav42",
  "uav43",
  "uav44",
  "uav45",
  "uav46",
  "uav47",
  "uav48",
  "uav49",
  "uav50",
  "uav51",
  "uav52",
  "uav53",
  "uav54",
  "uav55",
  "uav56",
  "uav57",
  "uav58",
  "uav59",
  "uav60",
  "uav61",
  "uav62",
  "uav63",
  "uav64",
  "uav65",
  "uav66",
  "uav67",
  "uav68",
  "uav69",
  "uav70",
  "uav71",
  "uav72",
  "uav73",
  "uav74",
  "uav75",
  "uav76",
  "uav77",
  "uav78",
  "uav79",
  "uav80",
  "uav81",
  "uav82",
  "uav83",
  "uav84",
  "uav85",
  "uav86",
  "uav87",
  "uav88",
  "uav89",
  "uav90",
  "uav91",
  "uav92",
  "uav93",
  "uav94",
  "uav95",
  "uav96",
  "uav97",
  "uav98",
  "uav99",
  "uav100",
  "uav101",
  "uav102",
  "uav103",
  "uav104",
  "uav105",
  "uav106",
  "uav107",
  "uav108",
  "uav109",
  "uav110",
  "uav111",
  "uav112",
  "uav113",
  "uav114",
  "uav115",
  "uav116",
  "uav117",
  "uav118",
  "uav119",
  "uav120",
  "uav121",
  "uav122",
  "uav123",
  "uav124",
  "uav125",
  "uav126",
  "uav127",
  "uav128",
  "uav129",
  "uav130",
  "uav131",
  "uav132",
  "uav133",
  "uav134",
  "uav135",
  "uav136",
  "uav137",
  "uav138",
  "uav139",
  "uav140",
  "uav141",
  "uav142",
  "uav143",
  "uav144",
  "uav145",
  "uav146",
  "uav147",
  "uav148",
  "uav149",
  "uav150",
  "uav151",
  "uav152",
  "uav153",
  "uav154",
  "uav155",
  "uav156",
  "uav157",
  "uav158",
  "uav159",
  "uav160",
  "uav161",
  "uav162",
  "uav163",
  "uav164",
  "uav165",
  "uav166",
  "uav167",
  "uav168",
  "uav169",
  "uav170",
  "uav171",
  "uav172",
  "uav173",
  "uav174",
  "uav175",
  "uav176",
  "uav177",
  "uav178",
  "uav179",
  "uav180",
  "uav181",
  "uav182",
  "uav183",
  "uav184",
  "uav185",
  "uav186",
  "uav187",
  "uav188",
  "uav189",
  "uav190",
  "uav191",
  "uav192",
  "uav193",
  "uav194",
  "uav195",
  "uav196",
  "uav197",
  "uav198",
  "uav199",
  "uav200",
  "uav201",
  "uav202",
  "uav203",
  "uav204",
  "uav205",
  "uav206",
  "uav207",
  "uav208",
  "uav209",
  "uav210",
  "uav211",
  "uav212",
  "uav213",
  "uav214",
  "uav215",
  "uav216",
  "uav217",
  "uav218",
  "uav219",
  "uav220",
  "uav221",
  "uav222",
  "uav223",
  "uav224",
  "uav225",
  "uav226",
  "uav227",
  "uav228",
  "uav229",
  "uav230",
  "uav231",
  "uav232",
  "uav233",
  "uav234",
  "uav235",
  "uav236",
  "uav237",
  "uav238",
  "uav239",
  "uav240",
  "uav241",
  "uav242",
  "uav243",
  "uav244",
  "uav245",
  "uav246",
  "uav247",
  "uav248",
  "uav249",
  "uav250",
  "uav251",
  "uav252",
  "uav253",
  "uav254",
  "uav255",
  "uav256",
  "uav257",
  "uav258",
  "uav259",
  "uav260",
  "uav261",
  "uav262",
  "uav263",
  "uav264",
  "uav265",
  "uav266",
  "uav267",
  "uav268",
  "uav269",
  "uav270",
  "uav271",
  "uav272",
  "uav273",
  "uav274",
  "uav275",
  "uav276",
  "uav277",
  "uav278",
  "uav279",
  "uav280",
  "uav281",
  "uav282",
  "uav283",
  "uav284",
  "uav285",
  "uav286",
  "uav287",
  "uav288",
  "uav289",
  "uav290",
  "uav291",
  "uav292",
  "uav293",
  "uav294",
  "uav295",
  "uav296",
  "uav297",
  "uav298",
  "uav299",
  "uav300",
  "uav301",
  "uav302",
  "uav303",
  "uav304",
  "uav305",
  "uav306",
  "uav307",
  "uav308",
  "uav309",
  "uav310",
  "uav311",
  "uav312",
  "uav313",
  "uav314",
  "uav315",
  "uav316",
  "uav317",
  "uav318",
  "uav319",
  "uav320",
  "uav321",
  "uav322",
  "uav323",
  "uav324",
  "uav325",
  "uav326",
  "uav327",
  "uav328",
  "uav329",
  "uav330",
  "uav331",
  "uav332",
  "uav333",
  "uav334",
  "uav335",
  "uav336",
  "uav337",
  "uav338",
  "uav339",
  "uav340",
  "uav341",
  "uav342",
  "uav343",
  "uav344",
  "uav345",
  "uav346",
  "uav347",
  "uav348",
  "uav349",
  "uav350",
  "uav351",
  "uav352",
  "uav353",
  "uav354",
  "uav355",
  "uav356",
  "uav357",
  "uav358",
  "uav359",
  "uav360",
  "uav361",
  "uav362",
  "uav363",
  "uav364",
  "uav365",
  "uav366",
  "uav367",
  "uav368",
  "uav369",
  "uav370",
  "uav371",
  "uav372",
  "uav373",
  "uav374",
  "uav375",
  "uav376",
  "uav377",
  "uav378",
  "uav379",
  "uav380",
  "uav381",
  "uav382",
  "uav383",
  "uav384",
  "uav385",
  "uav386",
  "uav387",
  "uav388",
  "uav389",
  "uav390",
  "uav391",
  "uav392",
  "uav393",
  "uav394",
  "uav395",
  "uav396",
  "uav397",
  "uav398",
  "uav399",
  "uav400",
]
